version: "3.9"
services:
  backend-server:
    container_name: backend-server
    build:
      context: payment
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
  frontend-server:
    container_name: frontend-server
    build:
      context: payment-front
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: